spring:
  profiles:
    active: local
---
server:
  port: 8084
    
logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  config:
    activate:
      on-profile: local
  application:
    name: ing-pay
  data:
    mongodb:
      host: localhost
      port: 27017
      database: example
      authentication-database: admin
      username: scott
      password: tiger
  kafka:
    bootstrap-servers: localhost:9091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: pay
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual-immediate
     
---
server:
  port: 8080
 
logging:
  level:
    yongs:
      temp: INFO
      
spring:
  config:
    activate:
      on-profile: container
  application:
    name: ing-pay
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      authentication-database: ${MONGODB_AUTH}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual-immediate
      